Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -44,7 +44,15 @@ jobs:
           DB_PASS="AwP680O6Ojwo"
           DB_NAME="mydb"
 
-          mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME"
+          # mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME"
+          timeout 60s mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "SELECT 1;" &> /dev/null
+
+          # Check exit status
+          if [ $? -eq 0 ]; then
+            echo "✅ Connected to MySQL database successfully."
+          else
+            echo "❌ Failed to connect to MySQL database."
+          fi
 
   # deploy:
   #   needs: prepare
