fix 10

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -176,8 +176,18 @@ jobs:
     if: ${{ needs.prepare.outputs.matrix != '' }}
     strategy:
       matrix:
-        lambda: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.lambda != 'None' && fromJSON(format('[{0}]', toJSON(github.event.inputs.lambda))) || (needs.find-modified-lambdas.outputs.lambdas == 'None' && fromJSON('["None"]') || fromJSON(needs.find-modified-lambdas.outputs.lambdas)) }}
-        layer: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.layer != 'None' && fromJSON(format('[{0}]', toJSON(github.event.inputs.layer))) || (needs.find-modified-lambdas.outputs.layers == 'None' && fromJSON('["None"]') || fromJSON(needs.find-modified-lambdas.outputs.layers)) }}
+        include: ${{ 
+          github.event_name == 'workflow_dispatch' && (
+            github.event.inputs.lambda != 'None' && fromJSON(format('[{{"type":"lambda","name":"{0}","env":"{1}","image":"{2}"}}]', github.event.inputs.lambda, fromJSON(needs.prepare.outputs.matrix).include[0].env, fromJSON(needs.prepare.outputs.matrix).include[0].image))
+            || github.event.inputs.layer != 'None' && fromJSON(format('[{{"type":"layer","name":"{0}","env":"{1}","image":"{2}"}}]', github.event.inputs.layer, fromJSON(needs.prepare.outputs.matrix).include[0].env, fromJSON(needs.prepare.outputs.matrix).include[0].image))
+            || fromJSON('[]')
+          ) || (
+            needs.find-modified-lambdas.outputs.lambdas != 'None' && needs.find-modified-lambdas.outputs.layers != 'None' && fromJSON(format('[{{"type":"lambda","name":"{0}","env":"{1}","image":"{2}"}},{{"type":"layer","name":"{3}","env":"{1}","image":"{2}"}}]', fromJSON(needs.find-modified-lambdas.outputs.lambdas)[0], fromJSON(needs.prepare.outputs.matrix).include[0].env, fromJSON(needs.prepare.outputs.matrix).include[0].image, fromJSON(needs.find-modified-lambdas.outputs.layers)[0]))
+            || needs.find-modified-lambdas.outputs.lambdas != 'None' && fromJSON(format('[{{"type":"lambda","name":"{0}","env":"{1}","image":"{2}"}}]', fromJSON(needs.find-modified-lambdas.outputs.lambdas)[0], fromJSON(needs.prepare.outputs.matrix).include[0].env, fromJSON(needs.prepare.outputs.matrix).include[0].image))
+            || needs.find-modified-lambdas.outputs.layers != 'None' && fromJSON(format('[{{"type":"layer","name":"{0}","env":"{1}","image":"{2}"}}]', fromJSON(needs.find-modified-lambdas.outputs.layers)[0], fromJSON(needs.prepare.outputs.matrix).include[0].env, fromJSON(needs.prepare.outputs.matrix).include[0].image))
+            || fromJSON('[]')
+          )
+        }}
       fail-fast: false
     runs-on: ubuntu-latest
     outputs:
@@ -185,8 +195,8 @@ jobs:
       BUILD_TARGET: ${{ steps.set-path.outputs.BUILD_TARGET }}
     environment: ${{ matrix.env }}
     env:
-      IMAGE_TAG: ${{ needs.prepare.outputs.matrix != '' && fromJSON(needs.prepare.outputs.matrix)[0].image || 'latest' }}
-      APP_ENV: ${{ needs.prepare.outputs.matrix != '' && fromJSON(needs.prepare.outputs.matrix)[0].env || 'ndev' }}
+      IMAGE_TAG: ${{ matrix.image }}
+      APP_ENV: ${{ matrix.env }}
       
     steps:
       - name: Checkout
@@ -204,28 +214,15 @@ jobs:
       - name: Determine Build Path
         id: set-path
         run: |
-          # For workflow_dispatch
-          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
-            echo "Detected manual trigger via workflow_dispatch."
-            if [[ "${{ github.event.inputs.lambda }}" != "None" && "${{ github.event.inputs.layer }}" != "None" ]]; then
-              echo "Error: You must select either 'lambda' OR 'layer', not both."
-              exit 1
-            elif [[ "${{ github.event.inputs.lambda }}" != "None" ]]; then
-              BUILD_PATH="root/lambda_functions/${{ github.event.inputs.lambda }}"
-              BUILD_TARGET="${{ github.event.inputs.lambda }}"
-            elif [[ "${{ github.event.inputs.layer }}" != "None" ]]; then
-              BUILD_PATH="root/layers/${{ github.event.inputs.layer }}"
-              BUILD_TARGET="${{ github.event.inputs.layer }}"
-            else
-              echo "Error: You must select either a 'lambda' or a 'layer' to proceed."
-              exit 1
-            fi
-          # For automated push (detected lambda from matrix)
+          if [[ "${{ matrix.type }}" == "lambda" ]]; then
+            BUILD_PATH="root/lambda_functions/${{ matrix.name }}"
+            BUILD_TARGET="${{ matrix.name }}"
+          elif [[ "${{ matrix.type }}" == "layer" ]]; then
+            BUILD_PATH="root/layers/${{ matrix.name }}"
+            BUILD_TARGET="${{ matrix.name }}"
           else
-            echo "Detected automated trigger via push."
-            echo "Matrix lambda: ${{ matrix.lambda }}"
-            BUILD_PATH="root/lambda_functions/${{ matrix.lambda }}"
-            BUILD_TARGET="${{ matrix.lambda }}"
+            echo "Error: Invalid matrix type."
+            exit 1
           fi
           
           echo "BUILD_PATH=${BUILD_PATH}" >> $GITHUB_ENV
@@ -233,15 +230,9 @@ jobs:
           echo "BUILD_PATH=${BUILD_PATH}" >> $GITHUB_OUTPUT
           echo "BUILD_TARGET=${BUILD_TARGET}" >> $GITHUB_OUTPUT
           
+          echo "Type: ${{ matrix.type }}"
           echo "BUILD_PATH: ${BUILD_PATH}"
           echo "BUILD_TARGET: ${BUILD_TARGET}"
-
-      - name: Check for lambdas or layers to build
-        run: |
-          if [[ "${{ matrix.lambda }}" == "None" && "${{ matrix.layer }}" == "None" ]]; then
-            echo "No lambdas or layers to build. Exiting."
-            exit 0
-          fi
 
       - name: Zip Lambda Layer Code
         if: ${{ env.APP_ENV == 'ndev' }}
