issue fix

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -172,6 +172,7 @@ jobs:
     needs:
       - prepare
       - find-modified-lambdas
+      - approval
     if: ${{ needs.prepare.outputs.matrix != '' }}
     strategy:
       matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
@@ -201,22 +202,31 @@ jobs:
       - name: Determine Build Path
         id: set-path
         run: |
-          if [[ "${{ github.event.inputs.lambda }}" != "None" && "${{ github.event.inputs.layer }}" != "None" ]]; then
-            echo "Error: You must select either 'lambda' OR 'layer', not both."
-            exit 1
-          elif [[ "${{ github.event.inputs.lambda }}" != "None" ]]; then
-            echo "BUILD_PATH=root/lambda_functions/${{ github.event.inputs.lambda }}" >> $GITHUB_ENV
-            echo "BUILD_TARGET=${{ github.event.inputs.lambda }}" >> $GITHUB_ENV
-            echo "BUILD_PATH=${{ env.BUILD_PATH }}" >> $GITHUB_OUTPUT
-            echo "BUILD_TARGET=${{ env.BUILD_TARGET }}" >> $GITHUB_OUTPUT
-          elif [[ "${{ github.event.inputs.layer }}" != "None" ]]; then
-            echo "BUILD_PATH=root/layers/${{ github.event.inputs.layer }}" >> $GITHUB_ENV
-            echo "BUILD_TARGET=${{ github.event.inputs.layer }}" >> $GITHUB_ENV
-            echo "BUILD_PATH=${{ env.BUILD_PATH }}" >> $GITHUB_OUTPUT
-            echo "BUILD_TARGET=${{ env.BUILD_TARGET }}" >> $GITHUB_OUTPUT
+          # For workflow_dispatch
+          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
+            if [[ "${{ github.event.inputs.lambda }}" != "None" && "${{ github.event.inputs.layer }}" != "None" ]]; then
+              echo "Error: You must select either 'lambda' OR 'layer', not both."
+              exit 1
+            elif [[ "${{ github.event.inputs.lambda }}" != "None" ]]; then
+              echo "BUILD_PATH=root/lambda_functions/${{ github.event.inputs.lambda }}" >> $GITHUB_ENV
+              echo "BUILD_TARGET=${{ github.event.inputs.lambda }}" >> $GITHUB_ENV
+              echo "BUILD_PATH=${{ env.BUILD_PATH }}" >> $GITHUB_OUTPUT
+              echo "BUILD_TARGET=${{ env.BUILD_TARGET }}" >> $GITHUB_OUTPUT
+            elif [[ "${{ github.event.inputs.layer }}" != "None" ]]; then
+              echo "BUILD_PATH=root/layers/${{ github.event.inputs.layer }}" >> $GITHUB_ENV
+              echo "BUILD_TARGET=${{ github.event.inputs.layer }}" >> $GITHUB_ENV
+              echo "BUILD_PATH=${{ env.BUILD_PATH }}" >> $GITHUB_OUTPUT
+              echo "BUILD_TARGET=${{ env.BUILD_TARGET }}" >> $GITHUB_OUTPUT
+            else
+              echo "Error: You must select either a 'lambda' or a 'layer' to proceed."
+              exit 1
+            fi
+          # For automated push (detected lambda from matrix)
           else
-            echo "Error: You must select either a 'lambda' or a 'layer' to proceed."
-            exit 1
+            echo "BUILD_PATH=root/lambda_functions/${{ matrix.lambda }}" >> $GITHUB_ENV
+            echo "BUILD_TARGET=${{ matrix.lambda }}" >> $GITHUB_ENV
+            echo "BUILD_PATH=${{ env.BUILD_PATH }}" >> $GITHUB_OUTPUT
+            echo "BUILD_TARGET=${{ env.BUILD_TARGET }}" >> $GITHUB_OUTPUT
           fi
       - name: Zip Lambda Layer Code
         if: ${{ env.APP_ENV == 'ndev' }}
